package com.mc.jfinal.model;

import com.mc.jfinal.model.base.BaseUserLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoginLog extends BaseUserLoginLog<UserLoginLog> {

}
