package com.mc.jfinal.model;

import com.jfinal.kit.StrKit;
import com.lsl.utils.DateUtil;
import com.mc.jfinal.model.base.BaseUser;
import com.mc.jfinal.service.UserService;
import com.mc.jfinal.utils.CommonConfig;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

}
